version: "3.9"

services:
  redis:
    image: redis:5
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  web:
    build: .
    command: > 
      bash -c "python src/manage.py migrate --noinput
      && python src/manage.py initadmin
      && python src/manage.py runserver 0.0.0.0:7777"
    volumes:
      - .:/code
    ports:
      - "7777:7777"

volumes:
  cache:
    driver: local
